---
version: '3'
services:
  terraboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      BASE_URL: /
    links:
      - db

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gorm
    volumes:
      - tb-data:/var/lib/postgresql/data

volumes:
  tb-data: {}
